const path=require("path");
const{getDatabaseFilePath}=require("../02_archivos_y_datos/YTPathService");
const{ensureUserDataFolders,ensureFolder}=require("../02_archivos_y_datos/YTFolderService");
const{exists,readJsonFile,writeJsonFile,getFileInfo}=require("../02_archivos_y_datos/YTFileService");
const{getProjectFolderPath,loadCurrentProject}=require("../06_proyectos/YTProjectStore");
function createClipSession(clips=null,timeline=null){return{app:"AutoEdit Studio",block:"08_clips_y_timeline",currentClips:clips,currentTimeline:timeline,updatedAt:new Date().toISOString()};}
function getClipSessionPath(){return getDatabaseFilePath("YTClipSession.json");}
function getProjectClipsPath(projectId){return path.join(getProjectFolderPath(projectId),"YTClips.json");}
function getProjectTimelinePath(projectId){return path.join(getProjectFolderPath(projectId),"YTTimeline.json");}
function ensureClipSession(){ensureUserDataFolders();if(!exists(getClipSessionPath()))writeJsonFile(getClipSessionPath(),createClipSession(null,null));return{ok:true,status:"OK",path:getClipSessionPath()};}
function getCurrentProjectRequired(){const current=loadCurrentProject();if(!current.currentProject||!current.currentProject.id)return{ok:false,status:"ERROR",message:"No hay proyecto actual. Primero crea un proyecto.",currentProject:null};return{ok:true,status:"OK",currentProject:current.currentProject};}
function loadClipSession(){ensureClipSession();const r=readJsonFile(getClipSessionPath(),createClipSession(null,null));return{ok:r.ok,status:r.ok?"OK":"ERROR",path:getClipSessionPath(),currentClips:r.data.currentClips||null,currentTimeline:r.data.currentTimeline||null,session:r.data,error:r.error||null};}
function saveClipSession(clips,timeline){ensureClipSession();const session=createClipSession(clips||null,timeline||null);writeJsonFile(getClipSessionPath(),session);return{ok:true,status:"OK",path:getClipSessionPath(),session};}
function saveClipsToProject(clipsCollection){ensureClipSession();const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;ensureFolder(getProjectFolderPath(project.id));const payload={...clipsCollection,projectId:project.id,projectName:project.name,updatedAt:new Date().toISOString()};const clipsPath=getProjectClipsPath(project.id);writeJsonFile(clipsPath,payload);const session=loadClipSession();saveClipSession(payload,session.currentTimeline||null);return{ok:true,status:"OK",clips:payload,clipsPath,file:getFileInfo(clipsPath)};}
function saveTimelineToProject(timeline){ensureClipSession();const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;ensureFolder(getProjectFolderPath(project.id));const payload={...timeline,projectId:project.id,projectName:project.name,updatedAt:new Date().toISOString()};const timelinePath=getProjectTimelinePath(project.id);writeJsonFile(timelinePath,payload);const session=loadClipSession();saveClipSession(session.currentClips||null,payload);return{ok:true,status:"OK",timeline:payload,timelinePath,file:getFileInfo(timelinePath)};}
function loadProjectClips(projectId){const clipsPath=getProjectClipsPath(projectId);if(!exists(clipsPath))return{ok:false,status:"EMPTY",projectId,clips:null,message:"El proyecto todavía no tiene clips."};const r=readJsonFile(clipsPath,null);return{ok:r.ok,status:r.ok?"OK":"ERROR",projectId,clipsPath,clips:r.data,error:r.error||null};}
function loadProjectTimeline(projectId){const timelinePath=getProjectTimelinePath(projectId);if(!exists(timelinePath))return{ok:false,status:"EMPTY",projectId,timeline:null,message:"El proyecto todavía no tiene timeline."};const r=readJsonFile(timelinePath,null);return{ok:r.ok,status:r.ok?"OK":"ERROR",projectId,timelinePath,timeline:r.data,error:r.error||null};}
module.exports={createClipSession,getClipSessionPath,getProjectClipsPath,getProjectTimelinePath,ensureClipSession,getCurrentProjectRequired,loadClipSession,saveClipSession,saveClipsToProject,saveTimelineToProject,loadProjectClips,loadProjectTimeline};
