const path=require("path");
const {getFolderPath,getDatabaseFilePath}=require("../02_archivos_y_datos/YTPathService");
const {ensureFolder,ensureUserDataFolders}=require("../02_archivos_y_datos/YTFolderService");
const {exists,readJsonFile,writeJsonFile,getFileInfo}=require("../02_archivos_y_datos/YTFileService");
const {createProjectsIndex,createCurrentProjectSession}=require("./YTProjectModel");
function getProjectsRootPath(){return getFolderPath("projects");}
function getProjectsIndexPath(){return getDatabaseFilePath("YTProjects.json");}
function getCurrentProjectPath(){return getDatabaseFilePath("YTCurrentProject.json");}
function getProjectFolderPath(projectId){return path.join(getProjectsRootPath(),projectId);}
function getProjectFilePath(projectId){return path.join(getProjectFolderPath(projectId),"YTProject.json");}
function ensureProjectStorage(){ensureUserDataFolders();ensureFolder(getProjectsRootPath());if(!exists(getProjectsIndexPath()))writeJsonFile(getProjectsIndexPath(),createProjectsIndex());if(!exists(getCurrentProjectPath()))writeJsonFile(getCurrentProjectPath(),createCurrentProjectSession(null));return{ok:true,status:"OK",projectsRoot:getProjectsRootPath(),indexPath:getProjectsIndexPath(),currentProjectPath:getCurrentProjectPath()};}
function loadProjectsIndex(){ensureProjectStorage();const r=readJsonFile(getProjectsIndexPath(),createProjectsIndex());return{ok:r.ok,status:r.ok?"OK":"ERROR",path:getProjectsIndexPath(),data:r.data||createProjectsIndex(),error:r.error||null};}
function saveProjectsIndex(indexData){ensureProjectStorage();const payload={...createProjectsIndex(),...(indexData||{}),updatedAt:new Date().toISOString()};writeJsonFile(getProjectsIndexPath(),payload);return{ok:true,status:"OK",path:getProjectsIndexPath(),data:payload};}
function saveProject(project){ensureProjectStorage();if(!project||!project.id)throw new Error("Proyecto inválido.");const folder=getProjectFolderPath(project.id);const file=getProjectFilePath(project.id);ensureFolder(folder);const payload={...project,updatedAt:new Date().toISOString()};writeJsonFile(file,payload);const index=loadProjectsIndex().data;const projects=Array.isArray(index.projects)?index.projects:[];const summary={id:payload.id,name:payload.name,slug:payload.slug,status:payload.status,videoName:payload.video?payload.video.name:"",videoPath:payload.video?payload.video.path:"",projectFolder:folder,projectFile:file,createdAt:payload.createdAt,updatedAt:payload.updatedAt};const i=projects.findIndex((p)=>p.id===payload.id);if(i>=0)projects[i]=summary;else projects.unshift(summary);saveProjectsIndex({...index,projects});return{ok:true,status:"OK",project:payload,projectFolder:folder,projectFile:file,file:getFileInfo(file)};}
function loadProject(projectId){ensureProjectStorage();const file=getProjectFilePath(projectId);if(!exists(file))return{ok:false,status:"ERROR",projectId,path:file,project:null,message:"El proyecto no existe."};const r=readJsonFile(file,null);return{ok:r.ok,status:r.ok?"OK":"ERROR",projectId,path:file,project:r.data,error:r.error||null};}
function listProjects(){const index=loadProjectsIndex();const projects=Array.isArray(index.data.projects)?index.data.projects:[];return{ok:index.ok,status:index.status,path:index.path,projects,count:projects.length};}
function saveCurrentProject(project){ensureProjectStorage();const session=createCurrentProjectSession(project||null);writeJsonFile(getCurrentProjectPath(),session);return{ok:true,status:"OK",path:getCurrentProjectPath(),currentProject:session.currentProject,session};}
function loadCurrentProject(){ensureProjectStorage();const r=readJsonFile(getCurrentProjectPath(),createCurrentProjectSession(null));return{ok:r.ok,status:r.ok?"OK":"ERROR",path:getCurrentProjectPath(),currentProject:r.data.currentProject||null,session:r.data,error:r.error||null};}
module.exports={getProjectsRootPath,getProjectsIndexPath,getCurrentProjectPath,getProjectFolderPath,getProjectFilePath,ensureProjectStorage,loadProjectsIndex,saveProjectsIndex,saveProject,loadProject,listProjects,saveCurrentProject,loadCurrentProject};
