const fs=require("fs");
const path=require("path");
const {ensureProjectStorage,getProjectsRootPath,getProjectsIndexPath,getCurrentProjectPath,listProjects,loadCurrentProject}=require("./YTProjectStore");
const {exists}=require("../02_archivos_y_datos/YTFileService");
const REQUIRED_FILES=["YTProjectModel.js","YTProjectStore.js","YTProjectService.js","YTProjectIpc.js","YTProjectCheck.js","YTProjectManual.md"];
function check(id,label,ok,message,recommendation=""){return{id,label,status:ok?"OK":"ERROR",ok,message,recommendation};}
function runProjectCheck(){const checks=[];const errors=[];const warnings=[];try{REQUIRED_FILES.forEach((fileName)=>{const ok=fs.existsSync(path.join(__dirname,fileName));checks.push(check("file:"+fileName,"Archivo "+fileName,ok,ok?"Archivo encontrado.":"Archivo faltante.","Crear "+fileName));if(!ok)errors.push("Falta archivo del Bloque 06: "+fileName);});ensureProjectStorage();const rootOk=exists(getProjectsRootPath());const indexOk=exists(getProjectsIndexPath());const currentOk=exists(getCurrentProjectPath());checks.push(check("projects:folder","Carpeta de proyectos",rootOk,rootOk?"user_data/projects existe.":"No existe user_data/projects."));checks.push(check("projects:index","Índice de proyectos",indexOk,indexOk?"YTProjects.json existe.":"No existe YTProjects.json."));checks.push(check("projects:current","Proyecto actual",currentOk,currentOk?"YTCurrentProject.json existe.":"No existe YTCurrentProject.json."));if(!rootOk)errors.push("No existe user_data/projects.");if(!indexOk)errors.push("No existe YTProjects.json.");if(!currentOk)errors.push("No existe YTCurrentProject.json.");const projects=listProjects();const current=loadCurrentProject();if(projects.count===0)warnings.push("Todavía no hay proyectos creados.");if(!current.currentProject)warnings.push("No hay proyecto actual.");checks.push({id:"projects:count",label:"Cantidad de proyectos",status:projects.count>0?"OK":"WARNING",ok:true,message:"Proyectos registrados: "+projects.count,recommendation:projects.count>0?"Sin acción requerida.":"Seleccionar video y crear proyecto."});checks.push({id:"projects:current-loaded",label:"Proyecto actual",status:current.currentProject?"OK":"WARNING",ok:true,message:current.currentProject?current.currentProject.name:"No hay proyecto actual.",recommendation:current.currentProject?"Sin acción requerida.":"Crear o abrir un proyecto."});const status=errors.length?"ERROR":warnings.length?"WARNING":"OK";return{ok:status!=="ERROR",approved:status==="OK",block:"06_proyectos",title:"Bloque 06 — Proyectos",status,summary:status==="OK"?"El Bloque 06 está correcto: proyectos disponibles.":status==="WARNING"?"El Bloque 06 funciona, pero todavía falta crear un proyecto.":"El Bloque 06 tiene errores.",checks,errors,warnings,projects,currentProject:current.currentProject,timestamp:new Date().toISOString()};}catch(error){return{ok:false,approved:false,block:"06_proyectos",title:"Bloque 06 — Proyectos",status:"ERROR",summary:"Error crítico ejecutando diagnóstico de proyectos.",checks,errors:[...errors,error.message||String(error)],warnings,timestamp:new Date().toISOString()};}}
if(require.main===module){const result=runProjectCheck();console.log(JSON.stringify(result,null,2));if(!result.ok)process.exitCode=1;}
module.exports={runProjectCheck};
