const{saveCurrentProjectChanges}=require("../06_proyectos/YTProjectService");
const{loadProjectAnalysis}=require("../07_transcripcion_y_analisis/YTTranscriptStore");
const{loadProjectClips,loadProjectTimeline}=require("../08_clips_y_timeline/YTClipStore");
const{createLayer,createLayerCollection,createDefaultStylePreset}=require("./YTStyleModel");
const{getCurrentProjectRequired,saveLayersToProject,saveStylePresetToProject,loadStyleSession,loadProjectLayers,loadProjectStylePreset,loadProjectSubtitles}=require("./YTStyleStore");
function getPrimaryKeyword(analysis){const keywords=analysis&&Array.isArray(analysis.keywords)?analysis.keywords:[];return keywords.length?keywords[0].word:"Contenido clave";}
function generateLayersFromProjectData(){const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;const analysisResult=loadProjectAnalysis(project.id);const clipsResult=loadProjectClips(project.id);const timelineResult=loadProjectTimeline(project.id);const subtitlesResult=loadProjectSubtitles(project.id);const analysis=analysisResult.analysis||{};const clips=clipsResult.clips&&Array.isArray(clipsResult.clips.clips)?clipsResult.clips.clips:[];const totalDuration=timelineResult.timeline?Number(timelineResult.timeline.totalDurationSeconds||30):30;const keyword=getPrimaryKeyword(analysis);const layers=[createLayer({id:"layer_hook",type:"text",name:"Hook inicial",text:keyword.toUpperCase(),position:"top",startSecond:0,endSecond:Math.min(5,totalDuration),zIndex:5}),createLayer({id:"layer_subtitles",type:"subtitles",name:"Subtítulos principales",text:subtitlesResult.ok?"Subtítulos activos":"Subtítulos pendientes",position:"bottom",startSecond:0,endSecond:totalDuration,zIndex:10}),createLayer({id:"layer_clip_badge",type:"badge",name:"Etiqueta de clip",text:clips.length?`${clips.length} clips sugeridos`:"Clip sugerido",position:"upper-right",startSecond:0,endSecond:totalDuration,zIndex:7}),createLayer({id:"layer_safe_frame",type:"guide",name:"Guía de zona segura",text:"safe-area",position:"full",startSecond:0,endSecond:totalDuration,zIndex:1,status:"GUIDE"})];const collection=createLayerCollection(layers,{projectId:project.id,projectName:project.name});const saved=saveLayersToProject(collection);if(!saved.ok)return saved;saveCurrentProjectChanges({layers:{status:collection.status,count:collection.count,layersPath:saved.layersPath,updatedAt:collection.updatedAt}});return{ok:true,status:"OK",message:"Capas visuales generadas correctamente.",layers:saved.layers,layersPath:saved.layersPath};}
function applyDefaultStylePreset(options={}){const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;const preset=createDefaultStylePreset({name:options.name||"Preset vertical profesional",format:options.format||"vertical_9_16"});const saved=saveStylePresetToProject(preset);if(!saved.ok)return saved;saveCurrentProjectChanges({stylePreset:{id:preset.id,name:preset.name,format:preset.format,stylePath:saved.stylePath,updatedAt:preset.updatedAt}});return{ok:true,status:"OK",message:"Preset de estilo aplicado correctamente.",stylePreset:saved.stylePreset,stylePath:saved.stylePath,project};}
function getCurrentStyleSession(){return loadStyleSession();}
function getStyleProjectDataForCurrentProject(){const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;return{ok:true,status:"OK",project,subtitles:loadProjectSubtitles(project.id),layers:loadProjectLayers(project.id),stylePreset:loadProjectStylePreset(project.id),session:loadStyleSession()};}
module.exports={generateLayersFromProjectData,applyDefaultStylePreset,getCurrentStyleSession,getStyleProjectDataForCurrentProject};
