function cleanText(text){return String(text||"").replace(/\r/g,"").replace(/[ \t]+/g," ").trim();}
function splitSentences(text){return cleanText(text).split(/(?<=[.!?¿¡])\s+|\n+/).map(x=>x.trim()).filter(Boolean);}
function roundSecond(value){const n=Number(value);if(!Number.isFinite(n)||n<0)return 0;return Math.round(n*100)/100;}
function createSubtitleLine(sentence="",index=1,startSecond=0,durationSeconds=4){const start=roundSecond(startSecond);const duration=Math.max(1.5,roundSecond(durationSeconds));return{id:`subtitle_${index}`,index,text:cleanText(sentence),startSecond:start,endSecond:roundSecond(start+duration),durationSeconds:duration,status:"READY"};}
function createSubtitleCollection(lines=[],context={}){return{app:"AutoEdit Studio",block:"09_subtitulos_capas_y_estilos",projectId:context.projectId||"",projectName:context.projectName||"",status:lines.length?"READY":"EMPTY",count:lines.length,language:context.language||"es",format:"internal-json",subtitles:lines,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};}
function createDefaultStylePreset(data={}){return{app:"AutoEdit Studio",block:"09_subtitulos_capas_y_estilos",id:data.id||"preset_default_vertical",name:data.name||"Preset vertical profesional",format:data.format||"vertical_9_16",canvas:{width:1080,height:1920,background:"#000000"},typography:{fontFamily:"Arial",titleSize:56,subtitleSize:46,subtitleWeight:"bold",subtitleCase:"normal"},colors:{primary:"#ffffff",accent:"#facc15",shadow:"#000000",panel:"rgba(0,0,0,0.55)"},subtitleBox:{position:"bottom",bottomMargin:230,maxWidthPercent:86,padding:24,radius:18},safeArea:{top:120,bottom:220,left:80,right:80},status:"READY",createdAt:data.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};}
function createLayer(data={}){return{id:data.id||`layer_${Date.now()}`,type:data.type||"text",name:data.name||"Capa",text:data.text||"",position:data.position||"center",startSecond:roundSecond(data.startSecond||0),endSecond:roundSecond(data.endSecond||5),zIndex:Number(data.zIndex||1),styleRef:data.styleRef||"preset_default_vertical",status:data.status||"READY",createdAt:data.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};}
function createLayerCollection(layers=[],context={}){return{app:"AutoEdit Studio",block:"09_subtitulos_capas_y_estilos",projectId:context.projectId||"",projectName:context.projectName||"",status:layers.length?"READY":"EMPTY",count:layers.length,layers,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};}
function createStyleSession(subtitles=null,layers=null,preset=null){return{app:"AutoEdit Studio",block:"09_subtitulos_capas_y_estilos",currentSubtitles:subtitles,currentLayers:layers,currentStylePreset:preset,updatedAt:new Date().toISOString()};}
module.exports={cleanText,splitSentences,roundSecond,createSubtitleLine,createSubtitleCollection,createDefaultStylePreset,createLayer,createLayerCollection,createStyleSession};
