const{saveCurrentProjectChanges}=require("../06_proyectos/YTProjectService");
const{loadProjectTranscript}=require("../07_transcripcion_y_analisis/YTTranscriptStore");
const{loadProjectTimeline}=require("../08_clips_y_timeline/YTClipStore");
const{splitSentences,createSubtitleLine,createSubtitleCollection}=require("./YTStyleModel");
const{getCurrentProjectRequired,saveSubtitlesToProject,loadStyleSession,loadProjectSubtitles}=require("./YTStyleStore");
function estimateTotalDuration(projectId,sentenceCount){const timeline=loadProjectTimeline(projectId);if(timeline.ok&&timeline.timeline&&Number(timeline.timeline.totalDurationSeconds)>0)return Number(timeline.timeline.totalDurationSeconds);return Math.max(12,sentenceCount*4);}
function generateSubtitlesFromTranscript(options={}){const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;const loadedTranscript=loadProjectTranscript(project.id);if(!loadedTranscript.ok||!loadedTranscript.transcript)return{ok:false,status:"ERROR",message:"No hay transcripción disponible. Primero guarda una transcripción.",project};const sentences=splitSentences(loadedTranscript.transcript.text);if(!sentences.length)return{ok:false,status:"ERROR",message:"La transcripción no tiene frases válidas para subtítulos."};const maxLines=Number(options.maxLines||80);const selected=sentences.slice(0,maxLines);const totalDuration=estimateTotalDuration(project.id,selected.length);const baseDuration=Math.max(2,totalDuration/selected.length);let cursor=0;const subtitles=selected.map((sentence,index)=>{const duration=Math.min(6,Math.max(2,baseDuration));const line=createSubtitleLine(sentence,index+1,cursor,duration);cursor+=duration;return line;});const collection=createSubtitleCollection(subtitles,{projectId:project.id,projectName:project.name,language:loadedTranscript.transcript.language||"es"});const saved=saveSubtitlesToProject(collection);if(!saved.ok)return saved;saveCurrentProjectChanges({subtitles:{status:collection.status,count:collection.count,subtitlesPath:saved.subtitlesPath,updatedAt:collection.updatedAt}});return{ok:true,status:"OK",message:"Subtítulos generados correctamente.",subtitles:saved.subtitles,subtitlesPath:saved.subtitlesPath};}
function getCurrentSubtitleSession(){return loadStyleSession();}
function getProjectSubtitlesForCurrentProject(){const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;return{ok:true,status:"OK",project,subtitles:loadProjectSubtitles(project.id),session:loadStyleSession()};}
module.exports={generateSubtitlesFromTranscript,getCurrentSubtitleSession,getProjectSubtitlesForCurrentProject};
