const {cleanText,countWords,createAnalysisRecord}=require("./YTTranscriptModel");
const STOP=new Set("a al algo ante antes aqui aquí asi así bajo bien cada como cómo con contra cual cuál cuando cuándo de del desde donde dónde dos el él ella ellos en entre era es esa ese eso esta está este esto estos fue ha hay la las le les lo los mas más me mi mis muy no nos o para pero por porque qué que se ser si sí sin sobre son su sus te un una uno y ya".split(" "));
function splitSentences(text){return cleanText(text).split(/(?<=[.!?¿¡])\s+|\n+/).map(s=>s.trim()).filter(Boolean);}
function norm(w){return String(w||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9ñ]/g,"").trim();}
function extractKeywords(text,limit=12){const counts=new Map();cleanText(text).split(/\s+/).map(norm).filter(w=>w.length>=4&&!STOP.has(w)).forEach(w=>counts.set(w,(counts.get(w)||0)+1));return[...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([word,count])=>({word,count}));}
function scoreSentence(sentence,keywords){const n=sentence.toLowerCase();let score=0;keywords.forEach(k=>{if(n.includes(k.word))score+=k.count;});if(sentence.length>=70&&sentence.length<=220)score+=3;if(/[¿?¡!]/.test(sentence))score+=2;if(/\b(importante|clave|error|problema|solución|resultado|recomendación|atención|ojo)\b/i.test(sentence))score+=4;return score;}
function extractImportantPhrases(text,keywords,limit=8){return splitSentences(text).map(s=>({text:s,score:scoreSentence(s,keywords)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit);}
function createSuggestedSegments(phrases){return phrases.slice(0,5).map((p,i)=>({id:"segment_"+(i+1),title:"Segmento sugerido "+(i+1),reason:"Frase con alto puntaje dentro del análisis textual.",text:p.text,score:p.score,startSecond:i*10,endSecond:i*10+8,status:"SUGGESTED"}));}
function summary(text,sentences){if(!text)return"Sin transcripción para analizar.";if(!sentences.length)return"La transcripción existe, pero no se detectaron frases completas.";return sentences.slice(0,3).join(" ");}
function analyzeTranscriptText(text,context={}){const cleaned=cleanText(text);const warnings=[];if(!cleaned)warnings.push("No hay texto de transcripción.");const sentences=splitSentences(cleaned);const keywords=extractKeywords(cleaned);const importantPhrases=extractImportantPhrases(cleaned,keywords);const suggestedSegments=createSuggestedSegments(importantPhrases);if(countWords(cleaned)<20)warnings.push("La transcripción es corta. El análisis será limitado.");return createAnalysisRecord({projectId:context.projectId||"",projectName:context.projectName||"",status:cleaned?"READY":"EMPTY",summary:summary(cleaned,sentences),wordCount:countWords(cleaned),sentenceCount:sentences.length,keywords,importantPhrases,suggestedSegments,warnings});}
module.exports={splitSentences,extractKeywords,extractImportantPhrases,createSuggestedSegments,analyzeTranscriptText};
