const path=require("path");
const {getDatabaseFilePath}=require("../02_archivos_y_datos/YTPathService");
const {ensureUserDataFolders,ensureFolder}=require("../02_archivos_y_datos/YTFolderService");
const {exists,readJsonFile,writeJsonFile,getFileInfo}=require("../02_archivos_y_datos/YTFileService");
const {getProjectFolderPath,loadCurrentProject}=require("../06_proyectos/YTProjectStore");
const {createTranscriptSession}=require("./YTTranscriptModel");
function getTranscriptSessionPath(){return getDatabaseFilePath("YTTranscriptSession.json");}
function getProjectTranscriptPath(projectId){return path.join(getProjectFolderPath(projectId),"YTTranscript.json");}
function getProjectAnalysisPath(projectId){return path.join(getProjectFolderPath(projectId),"YTAnalysis.json");}
function ensureTranscriptSession(){ensureUserDataFolders();if(!exists(getTranscriptSessionPath()))writeJsonFile(getTranscriptSessionPath(),createTranscriptSession(null,null));return{ok:true,status:"OK",path:getTranscriptSessionPath()};}
function getCurrentProjectRequired(){const current=loadCurrentProject();if(!current.currentProject||!current.currentProject.id)return{ok:false,status:"ERROR",message:"No hay proyecto actual. Primero crea un proyecto.",currentProject:null};return{ok:true,status:"OK",currentProject:current.currentProject};}
function loadTranscriptSession(){ensureTranscriptSession();const r=readJsonFile(getTranscriptSessionPath(),createTranscriptSession(null,null));return{ok:r.ok,status:r.ok?"OK":"ERROR",path:getTranscriptSessionPath(),currentTranscript:r.data.currentTranscript||null,currentAnalysis:r.data.currentAnalysis||null,session:r.data,error:r.error||null};}
function saveTranscriptToProject(transcript){ensureTranscriptSession();const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;ensureFolder(getProjectFolderPath(project.id));const payload={...transcript,projectId:project.id,projectName:project.name,updatedAt:new Date().toISOString()};const transcriptPath=getProjectTranscriptPath(project.id);writeJsonFile(transcriptPath,payload);const session=loadTranscriptSession();const newSession=createTranscriptSession(payload,session.currentAnalysis||null);writeJsonFile(getTranscriptSessionPath(),newSession);return{ok:true,status:"OK",transcript:payload,transcriptPath,file:getFileInfo(transcriptPath),session:newSession};}
function saveAnalysisToProject(analysis){ensureTranscriptSession();const current=getCurrentProjectRequired();if(!current.ok)return current;const project=current.currentProject;ensureFolder(getProjectFolderPath(project.id));const payload={...analysis,projectId:project.id,projectName:project.name,updatedAt:new Date().toISOString()};const analysisPath=getProjectAnalysisPath(project.id);writeJsonFile(analysisPath,payload);const session=loadTranscriptSession();const newSession=createTranscriptSession(session.currentTranscript||null,payload);writeJsonFile(getTranscriptSessionPath(),newSession);return{ok:true,status:"OK",analysis:payload,analysisPath,file:getFileInfo(analysisPath),session:newSession};}
function loadProjectTranscript(projectId){const transcriptPath=getProjectTranscriptPath(projectId);if(!exists(transcriptPath))return{ok:false,status:"EMPTY",projectId,transcript:null,message:"El proyecto todavía no tiene transcripción."};const r=readJsonFile(transcriptPath,null);return{ok:r.ok,status:r.ok?"OK":"ERROR",projectId,transcriptPath,transcript:r.data,error:r.error||null};}
function loadProjectAnalysis(projectId){const analysisPath=getProjectAnalysisPath(projectId);if(!exists(analysisPath))return{ok:false,status:"EMPTY",projectId,analysis:null,message:"El proyecto todavía no tiene análisis."};const r=readJsonFile(analysisPath,null);return{ok:r.ok,status:r.ok?"OK":"ERROR",projectId,analysisPath,analysis:r.data,error:r.error||null};}
module.exports={getTranscriptSessionPath,getProjectTranscriptPath,getProjectAnalysisPath,ensureTranscriptSession,getCurrentProjectRequired,saveTranscriptToProject,saveAnalysisToProject,loadTranscriptSession,loadProjectTranscript,loadProjectAnalysis};
