const path = require("path");

const PLATFORM_PRESETS = {
  youtube: { key: "youtube", name: "YouTube", format: "horizontal_16_9", width: 1920, height: 1080, fps: 30, videoBitrate: "6000k", audioBitrate: "192k", extension: ".mp4" },
  shorts: { key: "shorts", name: "YouTube Shorts", format: "vertical_9_16", width: 1080, height: 1920, fps: 30, videoBitrate: "4500k", audioBitrate: "160k", extension: ".mp4" },
  reels: { key: "reels", name: "Reels", format: "vertical_9_16", width: 1080, height: 1920, fps: 30, videoBitrate: "4500k", audioBitrate: "160k", extension: ".mp4" },
  square: { key: "square", name: "Formato cuadrado", format: "square_1_1", width: 1080, height: 1080, fps: 30, videoBitrate: "4500k", audioBitrate: "160k", extension: ".mp4" }
};

function cleanText(value, fallback = "") { return String(value || fallback || "").replace(/\s+/g, " ").trim(); }
function slugify(value, fallback = "autoedit") { const text = cleanText(value, fallback).toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, ""); return text || fallback; }
function getPlatformPreset(platformKey = "youtube") { return PLATFORM_PRESETS[platformKey] || PLATFORM_PRESETS.youtube; }
function listPlatformPresets() { return Object.values(PLATFORM_PRESETS).map((preset) => ({ ...preset })); }
function createExportId(projectName = "proyecto") { return `export_${slugify(projectName)}_${Date.now()}`; }
function createOutputFileName(projectName, platformKey) { const preset = getPlatformPreset(platformKey); const date = new Date().toISOString().slice(0, 10); return `${slugify(projectName, "proyecto")}_${preset.key}_${date}${preset.extension}`; }
function createExportItem(project, inputVideo, platformKey, outputFolder) { const preset = getPlatformPreset(platformKey); const fileName = createOutputFileName(project.name || inputVideo.name || "proyecto", preset.key); return { id: `${preset.key}_${Date.now()}`, platformKey: preset.key, platformName: preset.name, format: preset.format, width: preset.width, height: preset.height, fps: preset.fps, videoBitrate: preset.videoBitrate, audioBitrate: preset.audioBitrate, inputPath: inputVideo.path || "", outputFileName: fileName, outputPath: path.join(outputFolder, preset.key, fileName), status: "PENDING", message: "Pendiente de exportación.", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; }
function createExportPlan(data = {}) { const project = data.project || {}; const inputVideo = data.inputVideo || {}; const platforms = Array.isArray(data.platforms) && data.platforms.length ? data.platforms : ["youtube", "shorts", "reels", "square"]; const outputFolder = data.outputFolder || ""; const items = platforms.map((platformKey) => createExportItem(project, inputVideo, platformKey, outputFolder)); return { app: "AutoEdit Studio", block: "11_exportacion_y_publicacion", id: data.id || createExportId(project.name || inputVideo.name || "proyecto"), projectId: project.id || "", projectName: project.name || inputVideo.name || "Sin proyecto", inputVideo, outputFolder, platforms, count: items.length, items, status: items.length ? "READY" : "EMPTY", message: items.length ? "Plan de exportación creado." : "Plan vacío.", createdAt: data.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() }; }
function createPublicationPackage(data = {}) { const plan = data.plan || {}; const projectName = cleanText(plan.projectName || data.projectName, "Video AutoEdit"); const exportedFiles = Array.isArray(data.exportedFiles) ? data.exportedFiles : []; return { app: "AutoEdit Studio", block: "11_exportacion_y_publicacion", id: `publication_${slugify(projectName)}_${Date.now()}`, projectId: plan.projectId || "", projectName, title: cleanText(data.title, projectName), description: cleanText(data.description, "Video generado con AutoEdit Studio. Revisar título, miniatura, etiquetas y descripción antes de publicar."), tags: Array.isArray(data.tags) && data.tags.length ? data.tags : ["video", "autoedit"], checklist: [{ item: "Revisar audio", done: false }, { item: "Revisar subtítulos", done: false }, { item: "Revisar encuadre", done: false }, { item: "Crear miniatura", done: false }, { item: "Confirmar plataforma", done: false }], exportedFiles, status: exportedFiles.length ? "READY" : "DRAFT", message: exportedFiles.length ? "Paquete listo para revisar." : "Paquete creado como borrador.", createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; }

module.exports = { PLATFORM_PRESETS, cleanText, slugify, getPlatformPreset, listPlatformPresets, createExportId, createOutputFileName, createExportItem, createExportPlan, createPublicationPackage };
